name: dart_twitter_api
description: A dart wrapper for using the Twitter API with well documented interfaces for every endpoint.
version: 0.3.5
homepage: https://github.com/robertodoering/twitter_api
repository: https://github.com/robertodoering/twitter_api
issue_tracker: https://github.com/robertodoering/twitter_api/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 oauth1: ^1.0.6
 json_annotation: ^3.1.0
 intl: ^0.16.1
 http: ^0.12.2
 meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.5
  mockito: ^4.1.3
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
