name: twitter_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 oauth1: ^1.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
