name: dart_twitter_api
description: A dart wrapper for using the Twitter API with well documented interfaces for every endpoint.
version: 0.1.0+1
homepage: https://github.com/robertodoering/twitter_api
repository: https://github.com/robertodoering/twitter_api
issue_tracker: https://github.com/robertodoering/twitter_api/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 oauth1: ^1.0.4
 json_annotation: ^3.0.1
 intl: ^0.16.1
 http: ^0.12.1
 meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
